/*
 * 42videobricks
 *
 * 42videobricks is a Video Platform As A Service (VPaaS)
 *
 * The version of the OpenAPI document: 1.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Api42Vb.Model;
using Api42Vb.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Api42Vb.Test.Model
{
    /// <summary>
    ///  Class for testing DataVideoUsage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DataVideoUsageTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DataVideoUsage
        //private DataVideoUsage instance;

        public DataVideoUsageTests()
        {
            // TODO uncomment below to create an instance of DataVideoUsage
            //instance = new DataVideoUsage();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DataVideoUsage
        /// </summary>
        [Fact]
        public void DataVideoUsageInstanceTest()
        {
            // TODO uncomment below to test "IsType" DataVideoUsage
            //Assert.IsType<DataVideoUsage>(instance);
        }

        /// <summary>
        /// Test the property 'DateKey'
        /// </summary>
        [Fact]
        public void DateKeyTest()
        {
            // TODO unit test for the property 'DateKey'
        }

        /// <summary>
        /// Test the property 'Interval'
        /// </summary>
        [Fact]
        public void IntervalTest()
        {
            // TODO unit test for the property 'Interval'
        }

        /// <summary>
        /// Test the property 'Transcoding'
        /// </summary>
        [Fact]
        public void TranscodingTest()
        {
            // TODO unit test for the property 'Transcoding'
        }

        /// <summary>
        /// Test the property 'Hosting'
        /// </summary>
        [Fact]
        public void HostingTest()
        {
            // TODO unit test for the property 'Hosting'
        }

        /// <summary>
        /// Test the property 'Delivery'
        /// </summary>
        [Fact]
        public void DeliveryTest()
        {
            // TODO unit test for the property 'Delivery'
        }

        /// <summary>
        /// Test the property 'Drm'
        /// </summary>
        [Fact]
        public void DrmTest()
        {
            // TODO unit test for the property 'Drm'
        }
    }
}
