/*
 * 42videobricks
 *
 * 42videobricks is a Video Platform As A Service (VPaaS)
 *
 * The version of the OpenAPI document: 1.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Api42Vb.Model;
using Api42Vb.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Api42Vb.Test.Model
{
    /// <summary>
    ///  Class for testing Playlist
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PlaylistTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Playlist
        //private Playlist instance;

        public PlaylistTests()
        {
            // TODO uncomment below to create an instance of Playlist
            //instance = new Playlist();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Playlist
        /// </summary>
        [Fact]
        public void PlaylistInstanceTest()
        {
            // TODO uncomment below to test "IsType" Playlist
            //Assert.IsType<Playlist>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'Children'
        /// </summary>
        [Fact]
        public void ChildrenTest()
        {
            // TODO unit test for the property 'Children'
        }

        /// <summary>
        /// Test the property 'Ctime'
        /// </summary>
        [Fact]
        public void CtimeTest()
        {
            // TODO unit test for the property 'Ctime'
        }

        /// <summary>
        /// Test the property 'Mtime'
        /// </summary>
        [Fact]
        public void MtimeTest()
        {
            // TODO unit test for the property 'Mtime'
        }
    }
}
