/*
 * 42videobricks
 *
 * 42videobricks is a Video Platform As A Service (VPaaS)
 *
 * The version of the OpenAPI document: 1.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Api42Vb.Model;
using Api42Vb.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Api42Vb.Test.Model
{
    /// <summary>
    ///  Class for testing VideoMultipartUploadInitResponsePartsInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VideoMultipartUploadInitResponsePartsInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for VideoMultipartUploadInitResponsePartsInner
        //private VideoMultipartUploadInitResponsePartsInner instance;

        public VideoMultipartUploadInitResponsePartsInnerTests()
        {
            // TODO uncomment below to create an instance of VideoMultipartUploadInitResponsePartsInner
            //instance = new VideoMultipartUploadInitResponsePartsInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VideoMultipartUploadInitResponsePartsInner
        /// </summary>
        [Fact]
        public void VideoMultipartUploadInitResponsePartsInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" VideoMultipartUploadInitResponsePartsInner
            //Assert.IsType<VideoMultipartUploadInitResponsePartsInner>(instance);
        }

        /// <summary>
        /// Test the property 'SignedUrl'
        /// </summary>
        [Fact]
        public void SignedUrlTest()
        {
            // TODO unit test for the property 'SignedUrl'
        }

        /// <summary>
        /// Test the property 'PartNumber'
        /// </summary>
        [Fact]
        public void PartNumberTest()
        {
            // TODO unit test for the property 'PartNumber'
        }
    }
}
