/*
 * 42videobricks
 *
 * 42videobricks is a Video Platform As A Service (VPaaS)
 *
 * The version of the OpenAPI document: 1.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Api42Vb.Model;
using Api42Vb.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Api42Vb.Test.Model
{
    /// <summary>
    ///  Class for testing VideoMultipartUploadInit
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VideoMultipartUploadInitTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for VideoMultipartUploadInit
        //private VideoMultipartUploadInit instance;

        public VideoMultipartUploadInitTests()
        {
            // TODO uncomment below to create an instance of VideoMultipartUploadInit
            //instance = new VideoMultipartUploadInit();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VideoMultipartUploadInit
        /// </summary>
        [Fact]
        public void VideoMultipartUploadInitInstanceTest()
        {
            // TODO uncomment below to test "IsType" VideoMultipartUploadInit
            //Assert.IsType<VideoMultipartUploadInit>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Size'
        /// </summary>
        [Fact]
        public void SizeTest()
        {
            // TODO unit test for the property 'Size'
        }
    }
}
