/*
 * 42videobricks
 *
 * 42videobricks is a Video Platform As A Service (VPaaS)
 *
 * The version of the OpenAPI document: 1.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Api42Vb.Model;
using Api42Vb.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Api42Vb.Test.Model
{
    /// <summary>
    ///  Class for testing VideoAttachment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VideoAttachmentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for VideoAttachment
        //private VideoAttachment instance;

        public VideoAttachmentTests()
        {
            // TODO uncomment below to create an instance of VideoAttachment
            //instance = new VideoAttachment();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VideoAttachment
        /// </summary>
        [Fact]
        public void VideoAttachmentInstanceTest()
        {
            // TODO uncomment below to test "IsType" VideoAttachment
            //Assert.IsType<VideoAttachment>(instance);
        }

        /// <summary>
        /// Test the property 'VideoId'
        /// </summary>
        [Fact]
        public void VideoIdTest()
        {
            // TODO unit test for the property 'VideoId'
        }

        /// <summary>
        /// Test the property 'AttachmentType'
        /// </summary>
        [Fact]
        public void AttachmentTypeTest()
        {
            // TODO unit test for the property 'AttachmentType'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

        /// <summary>
        /// Test the property 'Locale'
        /// </summary>
        [Fact]
        public void LocaleTest()
        {
            // TODO unit test for the property 'Locale'
        }
    }
}
