/*
 * 42videobricks
 *
 * 42videobricks is a Video Platform As A Service (VPaaS)
 *
 * The version of the OpenAPI document: 1.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Api42Vb.Model;
using Api42Vb.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Api42Vb.Test.Model
{
    /// <summary>
    ///  Class for testing VideoMultipartUploadFinalize
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VideoMultipartUploadFinalizeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for VideoMultipartUploadFinalize
        //private VideoMultipartUploadFinalize instance;

        public VideoMultipartUploadFinalizeTests()
        {
            // TODO uncomment below to create an instance of VideoMultipartUploadFinalize
            //instance = new VideoMultipartUploadFinalize();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VideoMultipartUploadFinalize
        /// </summary>
        [Fact]
        public void VideoMultipartUploadFinalizeInstanceTest()
        {
            // TODO uncomment below to test "IsType" VideoMultipartUploadFinalize
            //Assert.IsType<VideoMultipartUploadFinalize>(instance);
        }

        /// <summary>
        /// Test the property 'FileId'
        /// </summary>
        [Fact]
        public void FileIdTest()
        {
            // TODO unit test for the property 'FileId'
        }

        /// <summary>
        /// Test the property 'FileKey'
        /// </summary>
        [Fact]
        public void FileKeyTest()
        {
            // TODO unit test for the property 'FileKey'
        }

        /// <summary>
        /// Test the property 'Parts'
        /// </summary>
        [Fact]
        public void PartsTest()
        {
            // TODO unit test for the property 'Parts'
        }
    }
}
