/*
 * 42videobricks
 *
 * 42videobricks is a Video Platform As A Service (VPaaS)
 *
 * The version of the OpenAPI document: 1.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Api42Vb.Model;
using Api42Vb.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Api42Vb.Test.Model
{
    /// <summary>
    ///  Class for testing VideoUploadInitResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VideoUploadInitResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for VideoUploadInitResponse
        //private VideoUploadInitResponse instance;

        public VideoUploadInitResponseTests()
        {
            // TODO uncomment below to create an instance of VideoUploadInitResponse
            //instance = new VideoUploadInitResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VideoUploadInitResponse
        /// </summary>
        [Fact]
        public void VideoUploadInitResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" VideoUploadInitResponse
            //Assert.IsType<VideoUploadInitResponse>(instance);
        }

        /// <summary>
        /// Test the property 'SignedUrl'
        /// </summary>
        [Fact]
        public void SignedUrlTest()
        {
            // TODO unit test for the property 'SignedUrl'
        }
    }
}
