/*
 * 42videobricks
 *
 * 42videobricks is a Video Platform As A Service (VPaaS)
 *
 * The version of the OpenAPI document: 1.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Api42Vb.Model;
using Api42Vb.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Api42Vb.Test.Model
{
    /// <summary>
    ///  Class for testing VideoMultipartUploadFinalizePartsInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VideoMultipartUploadFinalizePartsInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for VideoMultipartUploadFinalizePartsInner
        //private VideoMultipartUploadFinalizePartsInner instance;

        public VideoMultipartUploadFinalizePartsInnerTests()
        {
            // TODO uncomment below to create an instance of VideoMultipartUploadFinalizePartsInner
            //instance = new VideoMultipartUploadFinalizePartsInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VideoMultipartUploadFinalizePartsInner
        /// </summary>
        [Fact]
        public void VideoMultipartUploadFinalizePartsInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" VideoMultipartUploadFinalizePartsInner
            //Assert.IsType<VideoMultipartUploadFinalizePartsInner>(instance);
        }

        /// <summary>
        /// Test the property 'PartNumber'
        /// </summary>
        [Fact]
        public void PartNumberTest()
        {
            // TODO unit test for the property 'PartNumber'
        }

        /// <summary>
        /// Test the property 'ETag'
        /// </summary>
        [Fact]
        public void ETagTest()
        {
            // TODO unit test for the property 'ETag'
        }
    }
}
