/*
 * 42videobricks
 *
 * 42videobricks is a Video Platform As A Service (VPaaS)
 *
 * The version of the OpenAPI document: 1.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Api42Vb.Model;
using Api42Vb.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Api42Vb.Test.Model
{
    /// <summary>
    ///  Class for testing Video
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VideoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Video
        //private Video instance;

        public VideoTests()
        {
            // TODO uncomment below to create an instance of Video
            //instance = new Video();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Video
        /// </summary>
        [Fact]
        public void VideoInstanceTest()
        {
            // TODO uncomment below to test "IsType" Video
            //Assert.IsType<Video>(instance);
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'VarPublic'
        /// </summary>
        [Fact]
        public void VarPublicTest()
        {
            // TODO unit test for the property 'VarPublic'
        }

        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Fact]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'Duration'
        /// </summary>
        [Fact]
        public void DurationTest()
        {
            // TODO unit test for the property 'Duration'
        }

        /// <summary>
        /// Test the property 'Ctime'
        /// </summary>
        [Fact]
        public void CtimeTest()
        {
            // TODO unit test for the property 'Ctime'
        }

        /// <summary>
        /// Test the property 'Mtime'
        /// </summary>
        [Fact]
        public void MtimeTest()
        {
            // TODO unit test for the property 'Mtime'
        }

        /// <summary>
        /// Test the property 'Assets'
        /// </summary>
        [Fact]
        public void AssetsTest()
        {
            // TODO unit test for the property 'Assets'
        }

        /// <summary>
        /// Test the property 'Metas'
        /// </summary>
        [Fact]
        public void MetasTest()
        {
            // TODO unit test for the property 'Metas'
        }
    }
}
