/*
 * 42videobricks
 *
 * 42videobricks is a Video Platform As A Service (VPaaS)
 *
 * The version of the OpenAPI document: 1.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Api42Vb.Model;
using Api42Vb.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Api42Vb.Test.Model
{
    /// <summary>
    ///  Class for testing VideoAssets
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VideoAssetsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for VideoAssets
        //private VideoAssets instance;

        public VideoAssetsTests()
        {
            // TODO uncomment below to create an instance of VideoAssets
            //instance = new VideoAssets();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VideoAssets
        /// </summary>
        [Fact]
        public void VideoAssetsInstanceTest()
        {
            // TODO uncomment below to test "IsType" VideoAssets
            //Assert.IsType<VideoAssets>(instance);
        }

        /// <summary>
        /// Test the property 'Thumbnail'
        /// </summary>
        [Fact]
        public void ThumbnailTest()
        {
            // TODO unit test for the property 'Thumbnail'
        }

        /// <summary>
        /// Test the property 'Player'
        /// </summary>
        [Fact]
        public void PlayerTest()
        {
            // TODO unit test for the property 'Player'
        }

        /// <summary>
        /// Test the property 'Stream'
        /// </summary>
        [Fact]
        public void StreamTest()
        {
            // TODO unit test for the property 'Stream'
        }

        /// <summary>
        /// Test the property 'Iframe'
        /// </summary>
        [Fact]
        public void IframeTest()
        {
            // TODO unit test for the property 'Iframe'
        }
    }
}
