/*
 * 42videobricks
 *
 * 42videobricks is a Video Platform As A Service (VPaaS)
 *
 * The version of the OpenAPI document: 1.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Api42Vb.Model;
using Api42Vb.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Api42Vb.Test.Model
{
    /// <summary>
    ///  Class for testing Webhook
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WebhookTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Webhook
        //private Webhook instance;

        public WebhookTests()
        {
            // TODO uncomment below to create an instance of Webhook
            //instance = new Webhook();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Webhook
        /// </summary>
        [Fact]
        public void WebhookInstanceTest()
        {
            // TODO uncomment below to test "IsType" Webhook
            //Assert.IsType<Webhook>(instance);
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

        /// <summary>
        /// Test the property 'Token'
        /// </summary>
        [Fact]
        public void TokenTest()
        {
            // TODO unit test for the property 'Token'
        }

        /// <summary>
        /// Test the property 'EventType'
        /// </summary>
        [Fact]
        public void EventTypeTest()
        {
            // TODO unit test for the property 'EventType'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Ctime'
        /// </summary>
        [Fact]
        public void CtimeTest()
        {
            // TODO unit test for the property 'Ctime'
        }

        /// <summary>
        /// Test the property 'Mtime'
        /// </summary>
        [Fact]
        public void MtimeTest()
        {
            // TODO unit test for the property 'Mtime'
        }
    }
}
