/*
 * 42videobricks
 *
 * 42videobricks is a Video Platform As A Service (VPaaS)
 *
 * The version of the OpenAPI document: 1.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Api42Vb.Client.OpenAPIDateConverter;

namespace Api42Vb.Model
{
    /// <summary>
    /// Video Properties Object
    /// </summary>
    [DataContract(Name = "VideoProperties")]
    public partial class VideoProperties : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VideoProperties" /> class.
        /// </summary>
        /// <param name="title">title of the video.</param>
        /// <param name="description">description of the video.</param>
        /// <param name="varPublic">Define if the video is public (it can be accessible by anybody with the video url). Default &#x3D; tue.</param>
        /// <param name="tags">tags list linked to video.</param>
        public VideoProperties(string title = default(string), string description = default(string), bool varPublic = default(bool), List<string> tags = default(List<string>))
        {
            this.Title = title;
            this.Description = description;
            this.VarPublic = varPublic;
            this.Tags = tags;
        }

        /// <summary>
        /// title of the video
        /// </summary>
        /// <value>title of the video</value>
        /// <example>My video title</example>
        [DataMember(Name = "title", EmitDefaultValue = false)]
        public string Title { get; set; }

        /// <summary>
        /// description of the video
        /// </summary>
        /// <value>description of the video</value>
        /// <example>My video description</example>
        [DataMember(Name = "description", EmitDefaultValue = false)]
        public string Description { get; set; }

        /// <summary>
        /// Define if the video is public (it can be accessible by anybody with the video url). Default &#x3D; tue
        /// </summary>
        /// <value>Define if the video is public (it can be accessible by anybody with the video url). Default &#x3D; tue</value>
        /// <example>true</example>
        [DataMember(Name = "public", EmitDefaultValue = true)]
        public bool VarPublic { get; set; }

        /// <summary>
        /// tags list linked to video
        /// </summary>
        /// <value>tags list linked to video</value>
        /// <example>[&quot;MyTag&quot;]</example>
        [DataMember(Name = "tags", EmitDefaultValue = false)]
        public List<string> Tags { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VideoProperties {\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  VarPublic: ").Append(VarPublic).Append("\n");
            sb.Append("  Tags: ").Append(Tags).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Title (string) maxLength
            if (this.Title != null && this.Title.Length > 256)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Title, length must be less than 256.", new [] { "Title" });
            }

            // Description (string) maxLength
            if (this.Description != null && this.Description.Length > 500)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Description, length must be less than 500.", new [] { "Description" });
            }

            yield break;
        }
    }

}
