/*
 * 42videobricks
 *
 * 42videobricks is a Video Platform As A Service (VPaaS)
 *
 * The version of the OpenAPI document: 1.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Api42Vb.Client.OpenAPIDateConverter;

namespace Api42Vb.Model
{
    /// <summary>
    /// part signed url object
    /// </summary>
    [DataContract(Name = "VideoMultipartUploadFinalize_parts_inner")]
    public partial class VideoMultipartUploadFinalizePartsInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VideoMultipartUploadFinalizePartsInner" /> class.
        /// </summary>
        /// <param name="partNumber">part number.</param>
        /// <param name="eTag">part Etag.</param>
        public VideoMultipartUploadFinalizePartsInner(int partNumber = default(int), string eTag = default(string))
        {
            this.PartNumber = partNumber;
            this.ETag = eTag;
        }

        /// <summary>
        /// part number
        /// </summary>
        /// <value>part number</value>
        /// <example>1</example>
        [DataMember(Name = "PartNumber", EmitDefaultValue = false)]
        public int PartNumber { get; set; }

        /// <summary>
        /// part Etag
        /// </summary>
        /// <value>part Etag</value>
        /// <example>c30a42eb53926797181859fd42ef31fb</example>
        [DataMember(Name = "ETag", EmitDefaultValue = false)]
        public string ETag { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VideoMultipartUploadFinalizePartsInner {\n");
            sb.Append("  PartNumber: ").Append(PartNumber).Append("\n");
            sb.Append("  ETag: ").Append(ETag).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
